--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xXKarmaYTxX/PreventPlayerfromDropping
build-by-default: true
branches:
- main
projects:
  PreventPlayerfromDropping:
    path: ""
...
